### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by proyb6** [Asmod4n/mruby-hiredis#2]
I tried to experiment this with MRuby 1.3 in H2O web server,

```
mruby raised: /.../hiredis.rb:15: undefined method 'call' for #<Hiredis:0x1a1a9f8> (NoMethodError)
```

Source code:
```
class J
  def initialize
    @storage = Hiredis.new("localhost", 6379)
    @storage['foo'] = 'bar'
  end

  def call(env)
    body = JSON.generate({foo: @storage['foo']})

    [
      200,
      {'Content-Type'   => 'application/json',
       'Content-Length' => body.size},
       [body]
    ]
  end
end

J.new

```

**Comment by Asmod4n** [comment]
Have you tried this example, does it work there? https://github.com/jodosha/mruby-rack-json-api

When i use it outside of H2O my tests pass.

**Comment by proyb6** [comment]
I have managed to resolve with that repo. Thanks.

Trying your wrapper, is it a complete API features of what Hiredis has? I like to add ```expire``` by duration to a key which I'm not sure know it's done.

```All Redis Commands are mapped to Ruby Methods,```
Where do I find Redis methods in Ruby or is it suppose to be Redis?

**Comment by Asmod4n** [comment]
Every redis command is mapped as a ruby method automatically.

So expire would be
```ruby
hiredis.expire("key", 60)
```

**Comment by Asmod4n** [comment]
The syntax is taken 1:1 from https://redis.io/commands

**Comment by proyb6** [comment]
For increment on value, does it increment this way? I get ```undefined method 'incr' for "0" (NoMethodError)```

    @storage = Hiredis.new("localhost", 6379)
    @storage['noa'] = 0
    @storage['noa'].incr(1)

**Comment by Asmod4n** [comment]
Just do
```ruby
@storage.incr("noa", 1)
```

**Comment by proyb6** [comment]
Thank for your quick response, I appreciate it.
