### ISSUE TITLE
Incremental cannot be increase

### ISSUE THREAD

**Issue by proyb6** [Asmod4n/mruby-hiredis#3]
There is a bug which it doesn't increment, the value from noa would always return 1 when I tried to reload the page in H2O. I'm assume the call() method get execute on every page?

```
127.0.0.1:6379> GET noa
"1"
```

```
class J
  def initialize
    @r = Hiredis.new
#    @r['noa'] = 1     Commented out after key is existed in Redis
  end

  def call(env)
    @r.incr("noa", 1)
    body = JSON.generate({foo: @r["noa"]})

    [
      200,
      {'Content-Type'   => 'application/json',
       'Content-Length' => body.size},
       [body]
    ]
  end
end

J.new

```

**Comment by proyb6** [comment]
Sorry, I found it's actually ```@r.incr('noa')``` without the second parameters for this API.

**Comment by Asmod4n** [comment]
@proyb6 yeah, sorry.
That would be incrby i believe.
