### ISSUE TITLE
Bug in Async

### ISSUE THREAD

**Issue by proyb6** [Asmod4n/mruby-hiredis#4]
When I ran h2load benchmark, it threw out of memory error which I believe it's a bug in async and all ssh sessions in my macOS environment were crashed/exited as well.

I'm not sure if Hiredis async could be use in HTTP server?

Ubuntu 16.04 (July 2018 security patch)
H2O (latest master branch)
Redis latest

On H2O HTTP server h2o.conf:
```
  paths:
    "/asyncset":
      mruby.handler: |
        Proc.new do |env|
          async = Hiredis::Async.new
          async.queue(:set, "foo", "ba11111111111111")
          async.evloop.run_once
          [200, {'content-type' => 'text/html'}, ["asyncset"]]
        end
```

Unix socket has no issue:
```
Hiredis.new("/tmp/redis.sock", -1)
```

**Comment by Asmod4n** [comment]
@proyb6
Sorry for the very late reply, I haven't programmed in 4 years.

Hm, you have been creating a new connection for each request, that alone could lead to that issue.
But I've made some adjustments for long running Async sessions, please try again and fill another Issue if it still remains.
You should only create one connection in your code and keep on using that one.

**Comment by Asmod4n** [comment]
Updated tests and the Readme.
